### ISSUE TITLE
SNPEFF Error (Java string out of range)

### ISSUE THREAD

**Issue by slsevilla** [CCRGeneticsBranch/ngs_pipeline_4.2#5]
Error in rule [SNPEff](https://github.com/CCRGeneticsBranch/ngs_pipeline_4.2/blob/ba1f079fd2119dba9e6128c99e36d3c6f705ea3c/ngs_pipeline.rules#L873)

Example error log:
```
/data/khanlab/projects/processed_DATA/log/SNPEff.52233787.e
```

Example error:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at java.lang.String.substring(String.java:1911)
	at net.sf.samtools.tabix.TabixReader.parseReg(TabixReader.java:367)
	at net.sf.samtools.tabix.TabixReader.query(TabixReader.java:425)
	at ca.mcgill.mcb.pcingola.fileIterator.MarkerFileIterator.seek(MarkerFileIterator.java:199)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.findDbEntry(SnpSiftCmdDbNsfp.java:302)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.annotate(SnpSiftCmdDbNsfp.java:165)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.annotate(SnpSiftCmdDbNsfp.java:130)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.run(SnpSiftCmdDbNsfp.java:446)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.run(SnpSiftCmdDbNsfp.java:431)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSift.run(SnpSift.java:364)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSift.main(SnpSift.java:69)
[Sat Nov  5 04:57:16 2022]
```

I'm unable to determine where the local deployment of the pipeline is and therefore cannot find the "dbNSFP.txt.gz.tbi" file that is associated. Can you please update the location where this is @vinegang ?

**Comment by slsevilla** [comment]
Currently the tool is using a local instance of /snpEff/ dependent on the user's install. 

This is defined in the [Biowulf_snpEff.config](https://github.com/CCRGeneticsBranch/ngs_pipeline_4.2/blob/main/Tools_config/Biowulf_snpEff.config) parameter `data.dir`:
```
data.dir = /usr/local/apps/snpEff/4.1c/data/
```

This config is being passed through the rule snpEff (parameter `-c {params.snpEff_config}`). This is why it is failing for me - I do not have this installed locally and therefore do not have the db in this location.

Solution: To avoid this issue moving forward a few things should be changed:
1. Remove the data.dir from a /user/local/ to Biowulf
2. Add a path for the 'dbnsfp' instead of calling it local to the user. This would mean adding `-db /fdb/dbNSFP2/dbNSFP2.4.txt.gz` to the rule.
3. Add this path as a required input file. 
4. Add this file to the config for documentation and control.

@kopardev Anything else you can think of here?

Once I complete these changes I'm hoping I'll be able to get to the root of the sample failure that doesn't appear to be related to these issues.

**Comment by kopardev** [comment]
@slsevilla , I think the above solution should work!.. In fact, This is how BIOWULF recommended to run the SNPEFF module as per their documentation!

**Comment by vinegang** [comment]
We are using snpeff verision 4.1c in the ngs pipeline. I ran this version outside the pipeline and I was able to replicate the error. Another thing i noticed is despite the error snpsift and snpeff commands ran and generated the vcf file.

`Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at java.lang.String.substring(String.java:1911)
	at net.sf.samtools.tabix.TabixReader.parseReg(TabixReader.java:367)
	at net.sf.samtools.tabix.TabixReader.query(TabixReader.java:425)
	at ca.mcgill.mcb.pcingola.fileIterator.MarkerFileIterator.seek(MarkerFileIterator.java:199)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.findDbEntry(SnpSiftCmdDbNsfp.java:262)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.annotate(SnpSiftCmdDbNsfp.java:165)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.annotate(SnpSiftCmdDbNsfp.java:130)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.run(SnpSiftCmdDbNsfp.java:446)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdDbNsfp.run(SnpSiftCmdDbNsfp.java:431)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSift.run(SnpSift.java:364)
	at ca.mcgill.mcb.pcingola.snpSift.SnpSift.main(SnpSift.java:69)
`

I ran the same command with snpeff 4.3t and the script completed successfully without any error. The output from both the versions are very similar. I manually checked several lines.

`wc -l SJOS001112_M2_T_C663YACXX.HC_RNASeq.raw.snpEff.vcf SJOS001112_M2_T_C663YACXX.HC_RNASeq.raw.snpEff.vcf_4.1c`
       662796 SJOS001112_M2_T_C663YACXX.HC_RNASeq.raw.snpEff.vcf 
       662789 SJOS001112_M2_T_C663YACXX.HC_RNASeq.raw.snpEff.vcf_4.1c

I will do a 1-1 comparison and see if we are missing any variants in the 4.3t version. If everything looks good, we can consider moving to 4.3t or newer

**Comment by slsevilla** [comment]
Glad you found a working solution!

I wonder if it has to do with the db? Maybe it was created under / for 4.3 or higher?

**Comment by vinegang** [comment]
I updated the snpeff version to 4.3t, Xinyu is processing the samples and confirmed they did not error on snpeff after the update.
